[username]
format = "[$user]($style) on "
show_always = true
style_user = "149 bold"

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false
style = "green bold"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
